/** Пустая строка = запросы на /api через Vite proxy (dev). Иначе полный URL бэкенда. */
export const API_URL = (import.meta.env.VITE_API_URL as string | undefined)?.replace(/\/$/, '') ?? '';

export const config = {
    apiUrl: API_URL,
    endpoints: {
        register: `${API_URL}/api/auth/register/start`,
        login: `${API_URL}/api/auth/login/start`,
        auth: {
            registerStart: `${API_URL}/api/auth/register/start`,
            registerVerify: `${API_URL}/api/auth/register/verify`,
            registerResend: `${API_URL}/api/auth/register/resend`,
            loginStart: `${API_URL}/api/auth/login/start`,
            loginVerify: `${API_URL}/api/auth/login/verify`,
            loginResend: `${API_URL}/api/auth/login/resend`,
            google: `${API_URL}/api/auth/google`,
            googleConfig: `${API_URL}/api/auth/google-config`,
        },
        cookies: {
            consent: `${API_URL}/api/cookies/consent`,
        },
        captcha: {
            challenge: `${API_URL}/api/captcha/challenge`,
            verify: `${API_URL}/api/captcha/verify`,
        },
        qrSession: `${API_URL}/api/auth/qr-session`,
        events: `${API_URL}/api/events`,
        eventsRecommended: `${API_URL}/api/events/recommended`,
        faq: `${API_URL}/api/faq`,
        myTickets: `${API_URL}/api/Seats/my-tickets`,
        ticketRefundRequest: (ticketId: number) => `${API_URL}/api/Seats/tickets/${ticketId}/refund-request`,
        ticketTransfers: {
            incoming: `${API_URL}/api/ticket-transfers/incoming`,
            initiate: (ticketId: number) => `${API_URL}/api/ticket-transfers/tickets/${ticketId}`,
            detail: (id: number) => `${API_URL}/api/ticket-transfers/${id}`,
            decline: (id: number) => `${API_URL}/api/ticket-transfers/${id}/decline`,
            pay: (id: number) => `${API_URL}/api/ticket-transfers/${id}/pay`,
        },
        seatsCheckout: `${API_URL}/api/Seats/checkout`,
        notifications: `${API_URL}/api/notifications`,
        user: {
            me: `${API_URL}/api/user/me`,
            profile: `${API_URL}/api/user/profile`,
            notificationPrefs: `${API_URL}/api/user/notification-prefs`,
            avatar: `${API_URL}/api/user/avatar`,
        },
        catalogFilters: `${API_URL}/api/catalog-filters`,
        contact: `${API_URL}/api/contact/send`,
        organizer: {
            events: `${API_URL}/api/organizer/events`,
            uploadCover: `${API_URL}/api/organizer/events/upload-cover`,
            uploadLineupAvatar: `${API_URL}/api/organizer/events/upload-lineup-avatar`,
            assignOrganizer: (eventId: number) => `${API_URL}/api/organizer/events/${eventId}/assign-organizer`,
            cancellationRequestCode: (eventId: number) => `${API_URL}/api/organizer/events/${eventId}/cancellation/request-code`,
            cancellationResend: (eventId: number) => `${API_URL}/api/organizer/events/${eventId}/cancellation/resend`,
            cancellationSubmit: (eventId: number) => `${API_URL}/api/organizer/events/${eventId}/cancellation/submit`,
            cancellationRequest: (eventId: number) => `${API_URL}/api/organizer/events/${eventId}/cancellation-request`,
            deleteEvent: (eventId: number) => `${API_URL}/api/organizer/events/${eventId}`,
            submit: (eventId: number) => `${API_URL}/api/organizer/events/${eventId}/submit`,
            event: (eventId: number) => `${API_URL}/api/organizer/events/${eventId}`,
            schedulePublish: (eventId: number) => `${API_URL}/api/organizer/events/${eventId}/schedule-publish`,
            requestReschedule: (eventId: number) => `${API_URL}/api/organizer/events/${eventId}/request-reschedule`,
            rescheduleRequest: (eventId: number) => `${API_URL}/api/organizer/events/${eventId}/reschedule-request`,
            earnings: `${API_URL}/api/organizer/earnings`,
            venues: `${API_URL}/api/organizer/venues`,
            hallCatalog: `${API_URL}/api/organizer/hall-catalog`,
            layoutSeats: (layoutId: number) => `${API_URL}/api/organizer/layouts/${layoutId}/seats`,
            hallSetup: (eventId: number) => `${API_URL}/api/organizer/events/${eventId}/hall-setup`,
        },
        admin: {
            users: `${API_URL}/api/admin/users`,
            usersSearch: `${API_URL}/api/admin/users/search`,
            organizers: `${API_URL}/api/admin/users/organizers`,
            organizerRole: `${API_URL}/api/admin/users/organizer-role`,
            event: (id: number) => `${API_URL}/api/admin/events/${id}`,
            events: `${API_URL}/api/admin/events`,
            moderationEvents: `${API_URL}/api/admin/moderation/events`,
            approveEvent: (eventId: number) => `${API_URL}/api/admin/moderation/events/${eventId}/approve`,
            rejectEvent: (eventId: number) => `${API_URL}/api/admin/moderation/events/${eventId}/reject`,
            venues: `${API_URL}/api/admin/venues`,
            halls: `${API_URL}/api/admin/halls`,
            layouts: `${API_URL}/api/admin/layouts`,
            layoutSeats: (layoutId: number) => `${API_URL}/api/admin/layouts/${layoutId}/seats`,
            orders: `${API_URL}/api/admin/orders`,
            payments: `${API_URL}/api/admin/payments`,
            reviews: `${API_URL}/api/admin/reviews`,
            contactMessages: `${API_URL}/api/admin/contact-messages`,
            statistics: `${API_URL}/api/admin/statistics`,
            catalogFilters: `${API_URL}/api/admin/catalog-filters`,
            faq: `${API_URL}/api/admin/faq`,
            faqCategory: (id: string) => `${API_URL}/api/admin/faq/categories/${id}`,
            faqItems: `${API_URL}/api/admin/faq/items`,
            faqItem: (id: number) => `${API_URL}/api/admin/faq/items/${id}`,
            cancelEventRefundAll: (id: number) => `${API_URL}/api/admin/events/${id}/cancel-refund-all`,
            refundOrder: (id: number) => `${API_URL}/api/admin/orders/${id}/refund`,
            supportThreads: `${API_URL}/api/admin/support-threads`,
            supportThreadMessages: (id: number) => `${API_URL}/api/admin/support-threads/${id}/messages`,
            supportThreadReply: (id: number) => `${API_URL}/api/admin/support-threads/${id}/reply`,
            supportThreadStatus: (id: number) => `${API_URL}/api/admin/support-threads/${id}/status`,
            supportMessage: (id: number) => `${API_URL}/api/admin/support-messages/${id}`,
            rescheduleRequests: `${API_URL}/api/admin/reschedule-requests`,
            approveReschedule: (id: number) => `${API_URL}/api/admin/reschedule-requests/${id}/approve`,
            rejectReschedule: (id: number) => `${API_URL}/api/admin/reschedule-requests/${id}/reject`,
            cancellationRequests: `${API_URL}/api/admin/cancellation-requests`,
            approveCancellation: (id: number) => `${API_URL}/api/admin/cancellation-requests/${id}/approve`,
            rejectCancellation: (id: number) => `${API_URL}/api/admin/cancellation-requests/${id}/reject`,
            ticketRefundRequests: `${API_URL}/api/admin/ticket-refund-requests`,
            approveTicketRefund: (id: number) => `${API_URL}/api/admin/ticket-refund-requests/${id}/approve`,
            rejectTicketRefund: (id: number) => `${API_URL}/api/admin/ticket-refund-requests/${id}/reject`,
            cookieConsents: `${API_URL}/api/admin/cookie-consents`,
        },
        support: {
            thread: `${API_URL}/api/support/thread`,
            message: `${API_URL}/api/support/message`,
            escalate: `${API_URL}/api/support/escalate`,
        }
    }
}; 